import { useRef } from "react";
import type { CheatSheet } from "@shared/schema";
import { Download } from "lucide-react";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { Button } from "@/components/ui/button";

interface A4PreviewProps {
  data: NonNullable<CheatSheet['structuredContent']>;
}

export function A4Preview({ data }: A4PreviewProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleDownload = async () => {
    if (!contentRef.current) return;

    try {
      const canvas = await html2canvas(contentRef.current, {
        scale: 2, // Higher quality
        useCORS: true,
        backgroundColor: "#ffffff"
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      
      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      pdf.save(`${data.title || "cheat-sheet"}.pdf`);
    } catch (error) {
      console.error("Failed to generate PDF", error);
    }
  };

  return (
    <div className="flex flex-col items-center gap-6">
      <div className="w-full flex justify-end">
        <Button 
          onClick={handleDownload}
          className="bg-[#9CAF88] hover:bg-[#7d9169] text-white shadow-lg shadow-[#9CAF88]/20"
        >
          <Download className="mr-2 h-4 w-4" />
          Download PDF
        </Button>
      </div>

      <div className="overflow-auto w-full flex justify-center bg-[#f0f4ee] p-8 rounded-xl border border-[#d4e2cc] shadow-inner">
        <div 
          ref={contentRef}
          className="a4-paper bg-white relative flex flex-col gap-6 text-[#3c4633]"
        >
          {/* Header */}
          <div className="border-b-2 border-[#9CAF88] pb-4 mb-4">
            <h1 className="text-4xl font-bold font-display text-[#4c593f]">{data.title}</h1>
          </div>

          {/* Content Columns */}
          <div className="columns-2 gap-8 space-y-8">
            {data.sections.map((section, idx) => (
              <div 
                key={idx} 
                className="break-inside-avoid-column rounded-xl border border-[#d4e2cc] bg-[#fcfdfb] p-5 shadow-sm"
              >
                <h2 className="mb-3 text-lg font-bold text-[#627352] border-b border-[#ecf2e8] pb-2 font-display">
                  {section.heading}
                </h2>
                <ul className="space-y-2">
                  {section.points.map((point, pIdx) => (
                    <li key={pIdx} className="text-sm leading-relaxed text-[#3c4633] flex items-start gap-2">
                      <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-[#9CAF88]" />
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          {/* Footer Branding */}
          <div className="mt-auto border-t border-[#ecf2e8] pt-4 flex justify-between items-center text-xs text-[#9caf88]">
            <span className="font-bold">Generated by OneSheet</span>
            <span>{new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
